import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

public class grabPokemons {

    public static void main(String[] args) {
        String[] pokemonSets = {
                // "base-set",
                // "jungle",
                // "fossil",
                // "base-set-2",
                // "team-rocket",
                // "gym-heroes",
                // "gym-challenge",
                // "neo-genesis",
                // "neo-discovery",
                // "neo-revelation",
                // "neo-destiny",
                // "legendary-collection",
                // "expedition",
                // "aquapolis",
                // "skyridge",
                // "ruby-&-sapphire",
                // "sandstorm",
                // "dragon",
                // "team-magma-&-team-aqua",
                // "hidden-legends",
                // "fire-red-&-leaf-green",
                // "team-rocket-returns",
                // "deoxys",
                // "emerald",
                // "unseen-forces",
                // "delta-species",
                // "legend-maker",
                // "holon-phantoms",
                // "crystal-guardians",
                // "dragon-frontiers",
                // "power-keepers",
                // "diamond-&-pearl",
                // "mysterious-treasures",
                // "secret-wonders",
                // "great-encounters",
                // "majestic-dawn",
                // "legends-awakened",
                // "stormfront",
                // "platinum",
                // "rising-rivals",
                // "supreme-victors",
                // "arceus",
                // "heartgold-&-soulsilver",
                // "unleashed",
                // "undaunted",
                // "triumphant",
                // "call-of-legends",
                // "black-&-white",
                // "emerging-powers",
                // "noble-victories",
                // "next-destinies",
                // "dark-explorers",
                // "dragons-exalted",
                // "boundaries-crossed",
                // "plasma-storm",
                // "plasma-freeze",
                // "plasma-blast",
                // "legendary-treasures",
                // "xy",
                // "flashfire",
                // "furious-fists",
                // "phantom-forces",
                // "primal-clash",
                // "roaring-skies",
                // "ancient-origins",
                // "breakthrough",
                // "breakpoint",
                // "generations",
                // "fates-collide",
                // "steam-siege",
                // "evolutions",
                // "sun-&-moon",
                // "guardians-rising",
                // "burning-shadows",
                // "shining-legends",
                // "crimson-invasion",
                // "ultra-prism",
                // "forbidden-light",
                // "celestial-storm",
                // "dragon-majesty",
                // "lost-thunder",
                // "team-up",
                // "detective-pikachu",
                // "unbroken-bonds",
                // "unified-minds",
                // "hidden-fates",
                // "cosmic-eclipse",
                // "sword-&-shield",
                // "rebel-clash",
                // "darkness-ablaze",
                // "champion-27s-path",
                // "vivid-voltage",
                // "shining-fates",
                // "battle-styles",
                // "chilling-reign",
                // "evolving-skies",
                // "celebrations",
                // "fusion-strike",
                // "brilliant-stars",
                // "astral-radiance",
                // "go",
                // "lost-origin",
                // "silver-tempest",
                // "crown-zenith",
                // "scarlet-&-violet",
                // "paldea-evolved",
                // "obsidian-flames",
                // "scarlet-&-violet-151",
                // "paradox-rift",
                // "paldean-fates",
                // "temporal-forces",
                // "twilight-masquerade",
                // "shrouded-fable",
                // "stellar-crown",
                // "surging-sparks",
                "prismatic-evolutions",
                "journey-together",
                "destined-rivals",
                "black-bolt",
                "white-flare",
                "promo"
        };

        String[] jppokemonSets = {
                // "japanese-promo",
                // "japanese-expansion-pack",
                // "japanese-jungle",
                // "japanese-mystery-of-the-fossils",
                // "japanese-glory-of-team-rocket",
                // "japanese-leaders%27-stadium",
                // "japanese-challenge-from-the-darkness",
                // "japanese-gold-silver-new-world",
                // "japanese-crossing-the-ruins",
                // "japanese-awakening-legends",
                // "japanese-darkness-and-to-light",
                // "japanese-vs",
                // "japanese-web",
                // "japanese-the-town-on-no-map",
                // "japanese-wind-from-the-sea",
                // "japanese-split-earth",
                // "japanese-mysterious-mountains",
                // "japanese-miracle-of-the-desert",
                // "japanese-rulers-of-the-heavens",
                // "japanese-undone-seal",
                // "japanese-flight-of-legends",
                // "japanese-clash-of-the-blue-sky",
                // "japanese-rocket-gang-strikes-back",
                // "japanese-golden-sky-silvery-ocean",
                // "japanese-mirage-forest",
                // "japanese-holon-research",
                // "japanese-holon-phantom",
                // "japanese-miracle-crystal",
                // "japanese-offense-and-defense-of-the-furthest-ends",
                // "japanese-world-champions-pack",
                // "japanese-space-time",
                // "japanese-secret-of-the-lakes",
                // "japanese-shining-darkness",
                // "japanese-moonlit-pursuit",
                // "japanese-cry-from-the-mysterious",
                // "japanese-temple-of-anger",
                // "japanese-dawn-dash",
                // "japanese-intense-fight-in-the-destroyed-sky",
                // "japanese-galactic%27s-conquest",
                // "japanese-bonds-to-the-end-of-time",
                // "japanese-beat-of-the-frontier",
                // "japanese-advent-of-arceus",
                // "japanese-soulsilver-collection",
                // "japanese-reviving-legends",
                // "japanese-clash-at-the-summit",
                // "japanese-sword",
                // "japanese-shield",
                // "japanese-vmax-rising",
                // "japanese-rebel-clash",
                // "japanese-explosive-walker",
                // "japanese-infinity-zone",
                // "japanese-legendary-heartbeat",
                // "japanese-amazing-volt-tackle",
                // "japanese-shiny-star-v",
                // "japanese-single-strike-master",
                // "japanese-rapid-strike-master",
                // "japanese-matchless-fighter",
                // "japanese-silver-lance",
                // "japanese-jet-black-spirit",
                // "japanese-eevee-heroes",
                // "japanese-skyscraping-perfection",
                // "japanese-blue-sky-stream",
                // "japanese-fusion-arts",
                // "japanese-25th-anniversary-collection",
                // "japanese-vmax-climax",
                // "japanese-star-birth",
                // "japanese-battle-region",
                // "japanese-time-gazer",
                // "japanese-space-juggler",
                // "japanese-dark-phantasma",
                // "japanese-go",
                // "japanese-lost-abyss",
                // "japanese-incandescent-arcana",
                // "japanese-paradigm-trigger",
                // "japanese-vstar-universe",
                // "japanese-scarlet-ex",
                // "japanese-violet-ex",
                // "japanese-triplet-beat",
                // "japanese-snow-hazard",
                // "japanese-clay-burst",
                // "japanese-scarlet-&-violet-151",
                // "japanese-ruler-of-the-black-flame",
                // "japanese-raging-surf",
                // "japanese-ancient-roar",
                // "japanese-future-flash",
                // "japanese-mega-brave",
                // "japanese-mega-symphonia",
                // "japanese-shiny-treasure-ex",
                // "japanese-battle-partners",
                // "japanese-night-wanderer",
                // "japanese-cyber-judge",
                "japanese-terastal-festival"

        };

        ExecutorService executor = Executors.newFixedThreadPool(5);

        for (String setName : pokemonSets) {
            set set = new set();
            set.setSetName(setName);
            executor.execute(set);
        }

        for (String setName : jppokemonSets) {
            jpset set = new jpset();
            set.setSetName(setName);
            executor.execute(set);
        }

        executor.shutdown();

        try {
            executor.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}